-- delete from apm_tablaVersion

-- apm_tablaVersion - (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (1, 'PerfilSeccionCampo', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (2, 'PerfilSeccionCampoValor', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (3, 'PerfilSeccionCampoValorOpcion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (4, 'Aplicacion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (5, 'AplicacionBinarioVersion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (6, 'AplicacionParametro', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (7, 'AplicacionPerfil', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (8, 'AplicacionPerfilSeccion#1', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (9, 'AplicacionTabla', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (10, 'AplicacionTipoBinario', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (11, 'Campo', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (12, 'CampoValor', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (13, 'CampoValorOpcion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (14, 'DispositivoMovil', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (15, 'PerfilAcceso', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (16, 'PerfilAccesoAplicacion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (17, 'PerfilAccesoUsuario', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (18, 'Seccion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (19, 'UsuarioApm', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (25, 'TipoNotificacion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (26, 'EstadoNotificacion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (27, 'Notificacion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (28, 'UsuarioApmDM', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (29, 'AplicacionPerfilSeccion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (30, 'AplPerfilSeccionCampo', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (31, 'AplPerfilSeccionCampoValor', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (32, 'AplPerfilSeccionCampoValorOpcion', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (33, 'UsuarioApmImpresora', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (34, 'Area', 0, 'Tecso', DATETIME('NOW'), 1, 0)
INSERT INTO apm_tablaVersion (id, tabla, lastVersion, usuario, fechaUltMdf , estado, version) Values (35, 'AreaAplicacionPerfil', 0, 'Tecso', DATETIME('NOW'), 1, 0)
